name: hotel_booking_app
description: "Manage hotel bookings with ease using the Hotel Booking App."
publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.0
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  get: ^4.7.3
  hugeicons: ^1.1.4
  google_sign_in: ^6.2.2
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/images/icons/
